@startuml
skinparam linetype ortho
title Graphe des Dépendances des Plugins strongSwan

package "libtpmtss" {
  [tpm]
}

package "libstrongswan" {
  [fips_prf]
  [gcrypt]
  [wolfssl]
  [aes]
  [md4]
  [ldap]
  [revocation]
  [curl]
  [sha3]
  [des]
  [mgf1]
  [rdrand]
  [gcm]
  [kdf]
  [cmac]
  [gmp]
  [hmac]
  [mysql]
  [random]
  [sha1]
  [aesni]
  [pkcs1]
  [blowfish]
  [sshkey]
  [pkcs12]
  [dnskey]
  [rc2]
  [x509]
  [constraints]
  [chapoly]
  [curve25519]
  [test_vectors]
  [pkcs7]
  [winhttp]
  [sqlite]
  [pem]
  [ctr]
  [af_alg]
  [unbound]
  [pkcs11]
  [pubkey]
  [pkcs8]
  [ml]
  [padlock]
  [acert]
  [keychain]
  [soup]
  [openxpki]
  [md5]
  [xcbc]
  [pgp]
  [botan]
  [nonce]
  [sha2]
  [drbg]
  [agent]
  [files]
  [openssl]
  [ccm]
}

package "libimcv" {
  [imc_os]
  [imc_attestation]
  [imc_test]
  [imv_attestation]
  [imv_scanner]
  [imc_swima]
  [imc_scanner]
  [imv_test]
  [imv_os]
  [imv_swima]
  [imv_hcd]
  [imc_hcd]
}

package "libcharon" {
  [eap_radius]
  [tnc_pdp]
  [eap_ttls]
  [eap_simaka_pseudonym]
  [forecast]
  [ha]
  [socket_default]
  [updown]
  [duplicheck]
  [medsrv]
  [medcli]
  [p_cscf]
  [eap_identity]
  [connmark]
  [kernel_wfp]
  [eap_sim_pcsc]
  [selinux]
  [vici]
  [dnscert]
  [android_log]
  [eap_sim_file]
  [kernel_pfkey]
  [xauth_pam]
  [xauth_generic]
  [eap_aka]
  [coupling]
  [xauth_noauth]
  [osx_attr]
  [ext_auth]
  [whitelist]
  [error_notify]
  [dhcp]
  [bypass_lan]
  [unity]
  [addrblock]
  [radattr]
  [socket_win]
  [kernel_pfroute]
  [android_dns]
  [systime_fix]
  [led]
  [eap_peap]
  [stroke]
  [eap_mschapv2]
  [save_keys]
  [smp]
  [sql]
  [kernel_iph]
  [eap_simaka_sql]
  [eap_sim]
  [tnc_ifmap]
  [kernel_netlink]
  [eap_aka_3gpp2]
  [xauth_eap]
  [kernel_libipsec]
  [attr]
  [eap_tnc]
  [eap_dynamic]
  [eap_simaka_reauth]
  [socket_dynamic]
  [eap_aka_3gpp]
  [load_tester]
  [eap_gtc]
  [farp]
  [certexpire]
  [attr_sql]
  [lookip]
  [eap_tls]
  [resolve]
  [counters]
  [eap_md5]
  [ipseckey]
}

package "libtnccs" {
  [tnc_imv]
  [tnccs_dynamic]
  [tnccs_20]
  [tnccs_11]
  [tnc_tnccs]
  [tnc_imc]
}

[gcrypt] --> [gcrypt]
[gcrypt] --> [gpg-error]
[wolfssl] --> [wolfssl]
[ldap] --> [lber]
[ldap] --> [ldap]
[curl] --> [curl]
[gmp] --> [gmp]
[mysql] --> [MYSQLLIB]
[winhttp] --> [winhttp]
[sqlite] --> [sqlite3]
[unbound] --> [unbound]
[unbound] --> [ldns]
[soup] --> [{soup}]
[botan] --> [botan]
[openssl] --> [OPENSSL_LIB]
[forecast] --> [libiptc]
[connmark] --> [libiptc]
[kernel_wfp] --> [fwpuclnt]
[eap_sim_pcsc] --> [{pcsclite}]
[android_log] --> [log]
[socket_win] --> [ws2_32]
[android_dns] --> [cutils]
[smp] --> [{xml}]
[kernel_iph] --> [iphlpapi]
[kernel_netlink] --> [DLLIB]
[eap_aka_3gpp2] --> [gmp]
[tnccs_11] --> [{xml}]
@enduml
